#include <string>
#include <iostream>
#include <vector>
#include "matrix/Matrix.h"

using namespace std;

#define NUM_OF_THREADS 6

/* THE TEST VERIFIES THE CORRECTNESS OF RESULTS GENERATED BY PYTHON */

int main(){
    matrix::Matrix::create_threads(NUM_OF_THREADS);

    // пути к матрицам
    string left_path = "tests/leftN.mtx";
    string right_path = "tests/rightN.mtx";
    string ans_path = "temp/answerN.mtx";
    string res_path = "tests/resultN.mtx";

    bool final = true;

    auto start = std::chrono::system_clock::now();

    cout << "Testing:" << endl;
    for(char c = '1'; c <= '9'; ++c){
        left_path[10] = c;
        right_path[11] = c;
        ans_path[11] = c;
        res_path[12] = c;

        matrix::Matrix left(left_path);
        matrix::Matrix right(right_path);
        matrix::Matrix right_result(res_path);
        matrix::Matrix answer = left * right;

        bool compare = (right_result == answer);
        cout << "Test №" << c << ": " << (compare ? "TRUE" : "FALSE") << endl; 

        final &= compare;

        answer.to_file(ans_path);
    }

    auto end = std::chrono::system_clock::now();

    cout << "All tests correct: " 
        << (final ? "TRUE" : "FALSE") 
        << ", duration: " 
        << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() 
        << "ms" << endl;

    return 0;
}

